/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Use environment variables for Supabase credentials
// Handle both Vite (import.meta.env) and Node.js (process.env) environments
const getEnvVar = (viteKey: string, nodeKey: string): string => {
  // Check Vite env first (for browser/build)
  if (typeof import.meta !== 'undefined' && import.meta.env) {
    const viteValue = import.meta.env[viteKey];
    if (viteValue && viteValue !== 'undefined') return viteValue;
  }
  // Check Node.js process.env (for SSR/server)
  if (typeof process !== 'undefined' && process.env) {
    const nodeValue = process.env[nodeKey];
    if (nodeValue && nodeValue !== 'undefined') return nodeValue;
  }
  return '';
};

const supabaseUrl = getEnvVar('VITE_SUPABASE_URL', 'SUPABASE_URL') || 'https://kkdnnrwhzofttzajnwlj.supabase.co';
const supabaseAnonKey = getEnvVar('VITE_SUPABASE_ANON_KEY', 'SUPABASE_ANON_KEY') || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZG5ucndoem9mdHR6YWpud2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0Njk2ODAsImV4cCI6MjA3OTA0NTY4MH0.IVIEaP0Stc0AieekxDFMG_q76vu6KRRMsI_yIjOfmZM';

// Only warn in development, don't throw in production
if (!supabaseUrl || !supabaseAnonKey) {
  if (typeof window !== 'undefined' && window.location.hostname === 'localhost') {
    console.warn('Supabase credentials not configured. Please set SUPABASE_URL and SUPABASE_ANON_KEY environment variables.');
  }
}

export const projectId = supabaseUrl?.replace('https://', '').replace('.supabase.co', '') || '';
export const publicAnonKey = supabaseAnonKey || '';